stages:
  - build
  - test
  - push

variables:
  # 置空则使用当前日期
  VERSION: ""
  # 仅amd镜像是否上传
  AMD_PUSH: "false"
  # 构建的架构，置空默认为amd
  ARCH: "all"
  # 上传的镜像仓库，可选为dockerhub、aliyun、huawei
  PUSH_REPO: "dockerhub aliyun huawei"
  # 没啥用的变量
  MESSAGE: "中文支持1"
  # ----常量----
  IMAGE_NAME: "karthrand/flasktest"
  CONTAINER_NAME: "flasktest"
  test_except_str: Success

build_job:
  stage: build
  tags:
    - docker
  variables:
    GIT_DEPTH: "1"
  rules:
    # 仅在当前分支提交时message包含"镜像构建"时触发
    - if: "$CI_COMMIT_MESSAGE =~ /镜像构建/"
      when: on_success
    - when: never
  script:
    - |
      if [ -z "$VERSION" ]; then
        export VERSION=$(date +%Y%m%d)
        echo "当前默认版本为：$VERSION"
      else
        echo "手动设置版本为： $VERSION"
      fi
      if [ -z "$ARCH" ]; then
        export ARCH="amd64"
        echo "当前默认架构为：$ARCH"
      else
        echo "手动设置架构为： $ARCH"
      fi
      if [ ${ARCH} == "all" ]; then
          echo "构建AMD镜像: $IMAGE_NAME:$VERSION-amd64"
          echo "----------------------------------------"
          docker build -t $IMAGE_NAME:$VERSION-amd64 --build-arg ARCH=amd64 .
          echo "----------------------------------------"
          echo "构建ARM镜像: $IMAGE_NAME:$VERSION-arm64"
          docker buildx build --platform linux/arm64 -t $IMAGE_NAME:$VERSION-arm64  --build-arg ARCH=arm64 .
      elif [ ${ARCH} == "arm64" ]; then
          echo "构建ARM镜像: $IMAGE_NAME:$VERSION-arm64"
          docker buildx build --platform linux/arm64 -t $IMAGE_NAME:$VERSION-arm64  --build-arg ARCH=arm64 .
      else
          echo "构建AMD镜像: $IMAGE_NAME:$VERSION-amd64"
          docker build -t $IMAGE_NAME:$VERSION-amd64 --build-arg ARCH=amd64 .
      fi
      echo "export VERSION=$VERSION" > env.sh
      echo "export ARCH=$ARCH" >> env.sh
  artifacts:
    paths:
      - env.sh
    expire_in: 5 minutes

test_job:
  stage: test
  tags:
    - docker
  dependencies:
    - build_job
  rules:
    - if: "$CI_COMMIT_MESSAGE =~ /镜像构建/"
      when: on_success
    - when: never
  script:
    - |
      source env.sh
      export RANDOM_NUMBER_1=$(($RANDOM % 1000))
      export RANDOM_NUMBER_2=$(($RANDOM % 2000))
      echo "当前镜像版本为：$VERSION"
      echo "当前镜像架构为：$ARCH"
      func_test(){
        random_str=$1
        image_name=$2
        test_arch=$3
        echo "----------------------------------------"
        echo "当前测试镜像： ${image_name}"
        echo "当前测试架构：${test_arch}"
        echo "启动测试容器：${CONTAINER_NAME}-${random_str}"
        if [[ $test_arch == "arm64" ]]; then
            docker run --platform linux/arm64 --rm -d --privileged=true --name ${CONTAINER_NAME}-${random_str} $image_name
            echo "等待容器及服务就绪"
            sleep 35
        else
            docker run --rm -d --privileged=true --name ${CONTAINER_NAME}-${random_str} $image_name
            echo "等待容器及服务就绪"
            sleep 30
        fi
        ip=`docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ${CONTAINER_NAME}-${random_str}`
        echo "当前容器ip：${ip}"
        response=$(curl -s http://${ip}:5000/public) || true
        echo "返回判断：$response"
        if [[ "$response" == *${test_except_str}* ]]; then
            echo "正常: $response"
        else
            echo "错误: 期待响应返回${test_except_str}等, 但实际响应是: $response"
            exit 1
        fi
      }
      if [ ${ARCH} == "all" ]; then
          echo "export RANDOM_NUMBER_1=$RANDOM_NUMBER_1" >> env.sh
          echo "export RANDOM_NUMBER_2=$RANDOM_NUMBER_2" >> env.sh
          func_test $RANDOM_NUMBER_1 $IMAGE_NAME:$VERSION-amd64 amd64
          func_test $RANDOM_NUMBER_2 $IMAGE_NAME:$VERSION-arm64 arm64
      elif [ ${ARCH} == "arm64" ]; then
          echo "export RANDOM_NUMBER_2=$RANDOM_NUMBER_2" >> env.sh
          func_test $RANDOM_NUMBER_2 $IMAGE_NAME:$VERSION-amd64 amd64
      else
          echo "export RANDOM_NUMBER_1=$RANDOM_NUMBER_1" >> env.sh
          func_test $RANDOM_NUMBER_1 $IMAGE_NAME:$VERSION-arm64 arm64
      fi
  after_script:
    - |
      source env.sh
      if [ ${ARCH} == "all" ]; then
        echo "停止并删除AMD测试容器: ${CONTAINER_NAME}-${RANDOM_NUMBER_1}"
        docker stop ${CONTAINER_NAME}-${RANDOM_NUMBER_1}

        echo "停止并删除ARM测试容器: ${CONTAINER_NAME}-${RANDOM_NUMBER_2}"
        docker stop ${CONTAINER_NAME}-${RANDOM_NUMBER_2}

      elif [ ${ARCH} == "arm64" ]; then
        echo "停止并删除ARM测试容器: ${CONTAINER_NAME}-${RANDOM_NUMBER_2}"
        docker stop ${CONTAINER_NAME}-${RANDOM_NUMBER_2}
      else
        echo "停止并删除AMD测试容器: ${CONTAINER_NAME}-${RANDOM_NUMBER_1}"
        docker stop ${CONTAINER_NAME}-${RANDOM_NUMBER_1}
      fi

push_job:
  stage: push
  tags:
    - docker
  dependencies:
    - build_job
  rules:
    - if: "$CI_COMMIT_MESSAGE =~ /镜像构建/"
      when: on_success
    - when: never
  script:
    - |
      source env.sh
      echo "当前镜像版本为：$VERSION"
      echo "当前镜像架构为：$ARCH"
      echo "登录镜像仓库"

      func_amd64(){
          echo "上传: $IMAGE_NAME:$VERSION-amd64"
          docker tag $IMAGE_NAME:$VERSION-amd64 $DOCKER_REGISTRY/$IMAGE_NAME:$VERSION-amd64
          docker push $DOCKER_REGISTRY/$IMAGE_NAME:$VERSION-amd64
          if [ ${AMD_PUSH} == "true" ]; then
              echo "单架构上传: $IMAGE_NAME:latest"
              docker tag $DOCKER_REGISTRY/$IMAGE_NAME:$VERSION-amd64 $DOCKER_REGISTRY/$IMAGE_NAME:latest
              docker push $DOCKER_REGISTRY/$IMAGE_NAME:latest
          fi
      }

      func_arm64(){
          echo "上传: $IMAGE_NAME:$VERSION-arm64"
          docker tag $IMAGE_NAME:$VERSION-arm64 $DOCKER_REGISTRY/$IMAGE_NAME:$VERSION-arm64
          docker push  $DOCKER_REGISTRY/$IMAGE_NAME:$VERSION-arm64
      }

      func_mix(){
          echo "上传双架构镜像：$IMAGE_NAME:$VERSION"
          docker manifest create  $DOCKER_REGISTRY/$IMAGE_NAME:$VERSION --amend $DOCKER_REGISTRY/$IMAGE_NAME:$VERSION-amd64 --amend $DOCKER_REGISTRY/$IMAGE_NAME:$VERSION-arm64
          docker manifest push $DOCKER_REGISTRY/$IMAGE_NAME:$VERSION 

          echo "上传双架构镜像：$IMAGE_NAME:latest"
          docker manifest create  $DOCKER_REGISTRY/$IMAGE_NAME:latest --amend $DOCKER_REGISTRY/$IMAGE_NAME:$VERSION-amd64 --amend $DOCKER_REGISTRY/$IMAGE_NAME:$VERSION-arm64
          docker manifest push $DOCKER_REGISTRY/$IMAGE_NAME:latest
      }  

      push_repo_array=($PUSH_REPO)
      for repo in ${push_repo_array[@]}; do
          if [ ${repo} == "dockerhub" ]; then
              echo "添加代理"
              export http_proxy=http://192.168.1.4:7890
              export https_proxy=http://192.168.1.4:7890
              export no_proxy=localhost,127.0.0.1,10.96.0.0/12,192.168.59.0/24,192.168.49.0/24,192.168.39.0/24
              DOCKER_REGISTRY=docker.io
              echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USER --password-stdin $DOCKER_REGISTRY


          elif [ ${repo} == "aliyun" ]; then
              DOCKER_REGISTRY=registry.cn-hangzhou.aliyuncs.com
              echo $ALIYUN_PASSWORD | docker login --username $ALIYUN_USER --password-stdin $DOCKER_REGISTRY

          elif [ ${repo} == "huawei" ]; then
              DOCKER_REGISTRY=swr.cn-north-4.myhuaweicloud.com
              echo $HW_PASSWORD | docker login --username $HW_USER --password-stdin $DOCKER_REGISTRY
          fi
          echo "上传镜像到仓库: $DOCKER_REGISTRY/$IMAGE_NAME:$VERSION"
          if [ ${ARCH} == "all" ]; then
              func_amd64
              func_arm64
              func_mix
          elif [ ${ARCH} == "arm64" ]; then
              func_arm64
          else
              func_amd64
          fi

          if [ ${repo} == "dockerhub" ]; then
            echo "取消代理"
            unset http_proxy
            unset https_proxy
            unset no_proxy
          fi

      done
